import { Creator, Opportunity } from './types';

export const CREATORS: Creator[] = [
  {
    id: 1,
    name: 'Alia Vance',
    avatar: 'https://picsum.photos/seed/alia/200',
    title: 'Lifestyle & Travel Videographer',
    location: 'Bali, Indonesia',
    successScore: 98,
    rate: '$1,200 / project',
    bio: 'Capturing moments that tell a story. Specializing in aerial drone videography and authentic brand storytelling for travel and hospitality brands.',
    responseTime: '< 24h',
    completionRate: '100%',
    repeatClients: '82%',
    tags: ['travel', 'videography', 'drone', 'lifestyle', 'storytelling'],
    projects: [
      { id: 101, type: 'video', imageUrl: 'https://picsum.photos/seed/alia-proj1/400', role: 'Director & Editor', goal: 'Luxury Resort Promo Video', metrics: '3M+ views on Instagram Reels' },
      { id: 102, type: 'image', imageUrl: 'https://picsum.photos/seed/alia-proj2/400', role: 'Photographer', goal: 'Sustainable Fashion Campaign', metrics: 'Featured in Vogue' },
      { id: 103, type: 'video', imageUrl: 'https://picsum.photos/seed/alia-proj3/400', role: 'Drone Pilot', goal: 'Adventure Tourism Documentary', metrics: 'Increased tour bookings by 40%' },
      { id: 104, type: 'text', imageUrl: 'https://picsum.photos/seed/alia-proj4/400', role: 'Blogger', goal: 'Travel Guide for Solo Female Travelers', metrics: 'Top Google search result for "solo travel bali"' },
      { id: 105, type: 'audio', imageUrl: 'https://picsum.photos/seed/alia-proj5/400', role: 'Podcast Host', goal: 'Interview with a Local Artisan', metrics: '20K+ downloads in first week' },
      { id: 106, type: 'image', imageUrl: 'https://picsum.photos/seed/alia-proj6/400', role: 'Content Creator', goal: 'Food Photography Series', metrics: 'Partnered with 5-star restaurant' },
    ],
  },
  {
    id: 2,
    name: 'Kenji Tanaka',
    avatar: 'https://picsum.photos/seed/kenji/200',
    title: 'Tech & Gadget Reviewer',
    location: 'Tokyo, Japan',
    successScore: 95,
    rate: '$800 / video',
    bio: 'Unboxing the future. I provide in-depth, honest reviews of the latest tech, from smartphones to smart home devices. My goal is to help consumers make informed decisions.',
    responseTime: '< 48h',
    completionRate: '99%',
    repeatClients: '75%',
    tags: ['tech', 'unboxing', 'reviews', 'youtube', 'gadgets'],
    projects: [
      { id: 201, type: 'video', imageUrl: 'https://picsum.photos/seed/kenji-proj1/400', role: 'YouTuber', goal: 'Flagship Smartphone Review', metrics: '1.5M views, 5% conversion rate for affiliate links' },
      { id: 202, type: 'text', imageUrl: 'https://picsum.photos/seed/kenji-proj2/400', role: 'Writer', goal: '"Best Noise-Cancelling Headphones" Blog Post', metrics: 'Generated $15k in affiliate revenue' },
      { id: 203, type: 'image', imageUrl: 'https://picsum.photos/seed/kenji-proj3/400', role: 'Photographer', goal: 'Product Shots for a New Startup', metrics: 'Images used across all launch materials' },
      { id: 204, type: 'video', imageUrl: 'https://picsum.photos/seed/kenji-proj4/400', role: 'Content Creator', goal: '"A Day in My Smart Home" TikTok Series', metrics: 'Series went viral with 10M+ total views' },
      { id: 205, type: 'audio', imageUrl: 'https://picsum.photos/seed/kenji-proj5/400', role: 'Podcast Guest', goal: 'Discussing AI in consumer tech', metrics: 'Reached #1 on tech podcast charts' },
      { id: 206, type: 'video', imageUrl: 'https://picsum.photos/seed/kenji-proj6/400', role: 'Editor', goal: 'Gaming Laptop Performance Test', metrics: 'Praised for technical editing and clear benchmarks' },
    ],
  },
  {
    id: 3,
    name: 'Isabella Rossi',
    avatar: 'https://picsum.photos/seed/isabella/200',
    title: 'Food Stylist & Recipe Developer',
    location: 'Milan, Italy',
    successScore: 99,
    rate: '$1,500 / project',
    bio: 'Making food beautiful. From developing unique recipes for CPG brands to styling for editorial photoshoots, I bring a touch of Italian elegance to every project.',
    responseTime: '< 12h',
    completionRate: '100%',
    repeatClients: '90%',
    tags: ['food', 'recipe', 'stylist', 'photography', 'culinary'],
    projects: [
      { id: 301, type: 'image', imageUrl: 'https://picsum.photos/seed/isabella-proj1/400', role: 'Food Stylist', goal: 'Cookbook Cover Shoot', metrics: 'NYT Bestseller' },
      { id: 302, type: 'video', imageUrl: 'https://picsum.photos/seed/isabella-proj2/400', role: 'Recipe Developer', goal: 'Pasta-making tutorial for a food blog', metrics: '500k shares on Pinterest' },
      { id: 303, type: 'text', imageUrl: 'https://picsum.photos/seed/isabella-proj3/400', role: 'Author', goal: 'E-book on Italian Desserts', metrics: '10,000+ copies sold' },
      { id: 304, type: 'image', imageUrl: 'https://picsum.photos/seed/isabella-proj4/400', role: 'Photographer', goal: 'Menu photography for a Michelin restaurant', metrics: 'Resulted in a 30% increase in reservations' },
      { id: 305, type: 'video', imageUrl: 'https://picsum.photos/seed/isabella-proj5/400', role: 'Host', goal: 'Instagram Live Cooking Class', metrics: 'Reached 25k live viewers' },
      { id: 306, type: 'audio', imageUrl: 'https://picsum.photos/seed/isabella-proj6/400', role: 'Consultant', goal: 'Flavor profile development for a new snack brand', metrics: 'Product successfully launched in major supermarkets' },
    ],
  },
];


export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 1,
    companyName: 'Starlight Coffee Co.',
    companyLogo: 'https://picsum.photos/seed/starlight-logo/100',
    jobTitle: 'Lifestyle Product Photography',
    budget: '$1,500 - $2,500',
    description: 'We are launching a new line of artisanal coffee beans and need a stunning set of lifestyle photos for our website, social media, and press kits.',
    requiredSkills: ['product-photography', 'lifestyle', 'food-styling', 'editing'],
    projectType: 'image',
  },
  {
    id: 2,
    companyName: 'Nomad Adventures',
    companyLogo: 'https://picsum.photos/seed/nomad-logo/100',
    jobTitle: 'Reels/TikTok Video Editor',
    budget: '$3,000 / month (retainer)',
    description: 'Looking for a talented video editor to create 10-15 engaging short-form videos per month for our travel brand. Raw footage will be provided.',
    requiredSkills: ['video-editing', 'reels', 'storytelling', 'color-grading'],
    projectType: 'video',
  },
  {
    id: 3,
    companyName: 'Future Forward Tech',
    companyLogo: 'https://picsum.photos/seed/future-logo/100',
    jobTitle: 'Unboxing & Review Video Host',
    budget: '$1,000 / video',
    description: 'Seeking a charismatic host to create a series of YouTube videos reviewing our latest consumer gadgets. Must be comfortable on camera and knowledgeable about tech.',
    requiredSkills: ['on-camera-talent', 'tech-reviews', 'youtube', 'script-writing'],
    projectType: 'video',
  },
];
